// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jmxemujffofqpqrxajlb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpteGVtdWpmZm9mcXBxcnhhamxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2ODcwMTIsImV4cCI6MjA3NTI2MzAxMn0.bkRTuYwzbW1WpcvpUq0G2Oecc9N32TVOcNYmmZVQ5hA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);